name: example
description: Examples for async_redux.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  http: ^1.1.0
  async_redux:
    path: ../
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.4

dev_dependencies:
  test: ^1.16.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
