name: example
description: Examples for async_redux.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  async_redux:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.6.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
