name: async_redux
description: The modern version of Redux. State management that's simple to learn and easy to use; Powerful enough to handle complex applications with millions of users; Testable.
version: 26.4.2
# author: Marcelo Glasberg <marcglasberg@gmail.com>
repository: https://github.com/marcglasberg/async_redux
issue_tracker: https://github.com/marcglasberg/async_redux/issues
homepage: https://asyncredux.com
documentation: https://asyncredux.com
topics:
  - redux
  - state-management
  - ui
  - reactive-programming
  - testing

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  async_redux_core: ^1.4.1
  fast_immutable_collections: ^11.1.0
  weak_map: ^4.0.1
  connectivity_plus: ">=6.0.3 <8.0.0"
  collection: ^1.18.0
  logging: ^1.3.0
  path: ^1.9.1
  file: ^7.0.0
  path_provider: ^2.1.5
  meta: ^1.11.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_async: ^1.3.3
  bdd_framework: ^4.0.6
