name: async_redux
description: Redux without the boilerplate, tailored for Flutter. Easy to learn, to use and test. Allows for both sync and async reducers.
version: 7.0.2
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/async_redux

environment:
  sdk: ">=2.9.3 <3.0.0"

dependencies:
  logging: ^0.11.4
  path: ^1.6.4
  path_provider: ^1.6.7
  file: ^6.0.0-nullsafety.2
  weak_map: ^1.3.1
  fast_immutable_collections: ^1.0.10
  meta: ^1.1.8
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.6.3
  async: ^2.4.1
  flutter_test:
    sdk: flutter

flutter:

