name: async_redux
description: Redux without the boilerplate, tailored for Flutter. Easy to learn, to use and test. Allows for both sync and async reducers.
version: 12.0.0
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/async_redux

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.1
  path: ^1.8.0
  path_provider: ^2.0.1
  file: ^6.1.0
  weak_map: ^2.0.2
  fast_immutable_collections: ^5.0.0
  collection: ^1.15.0
  meta: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.8
  flutter_test:
    sdk: flutter

flutter:

