name: async_redux
description: A special Redux version, tailored for Flutter, which is easy to learn, to use, to test, and has no boilerplate. Allows for both sync and async reducers.
version: 1.3.4
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/async_redux

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  logging: ^0.11.3+2
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.6.3
  flutter_test:
    sdk: flutter

flutter:

